# Generated by Django 3.2.9 on 2021-11-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tempereture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempereture_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.passengers')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.passengers')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.passengers')),
            ],
        ),
    ]
